### ISSUE TITLE
False positive if query has leading whitespace

### ISSUE THREAD

**Issue by leonid-shevtsov** [lufeee/execinquery#4]
In our code we have SQL in constants, and for readability they start with an empty line:

```
err := s.db.QueryRow(someSQL).Scan(&foo)

const someSQL = `
  SELECT foo 
  FROM bar
  WHERE ...query continues
`
```

On this input we get an `execinquery` error:

```
It's better to use Execute method instead of QueryRow method to execute `` query
```

Suggestion: `TrimLeft` the query string.

**Comment by lufeee** [comment]
Have we met your request?

**Comment by leonid-shevtsov** [comment]
Thanks, judging by the test cases #10 should fix it.
