### ISSUE TITLE
incorrect match

### ISSUE THREAD

**Issue by Hades32** [lufeee/execinquery#5]
The following snippet is incorrectly recognized by the linter:
```go
package query

import "context"

const selectCodes = `-- name: SelectCodeForUpdate :one
SELECT code, max_uses, uses, ttl, enabled, created_at, updated_at
FROM codes
AS OF SYSTEM TIME follower_read_timestamp()
WHERE code = $1
`

func (q *Queries) SelectRegisterCodeFollowerRead(ctx context.Context, code string) (Code, error) {
	row := q.db.QueryRow(ctx, selectCodes , code)
	var i RegisterBonusCode
	err := row.Scan(
		&i.Code,
		&i.MaxUses,
		&i.Uses,
		&i.Ttl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
```

@lufeee

**Comment by lufeee** [comment]
Am I correct that your request is to disable comments?

**Comment by Hades32** [comment]
The SQL is a select and therefore my request is for the linter to not complain. If you think it's enough to skip comments (and whitespace) for the check, then I'm fine with that approach. 

PS: this code is generated by SQLC so this issue will probably hit quite a few folks
